import { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    name: "High-Yield Savings Account",
    interestRate: "1.50%",
    term: "12 months",
    minimumDeposit: "£1,000",
    maximumDeposit: "£250,000",
    link: "https://example.com/product1",
    logo: "/images/logo1.jpg",
  },
  {
    id: 2,
    name: "Fixed Deposit Account",
    interestRate: "2.00%",
    term: "24 months",
    minimumDeposit: "£5,000",
    maximumDeposit: "£500,000",
    link: "https://example.com/product2",
    logo: "/images/logo1.jpg",
  },
  {
    id: 3,
    name: "Flexible Savings Account",
    interestRate: "1.75%",
    term: "18 months",
    minimumDeposit: "£2,000",
    maximumDeposit: "£300,000",
    link: "https://example.com/product3",
    logo: "/images/logo1.jpg",
  },
  {
    id: 4,
    name: "Investment Account",
    interestRate: "2.25%",
    term: "36 months",
    minimumDeposit: "£10,000",
    maximumDeposit: "£1,000,000",
    link: "https://example.com/product4",
    logo: "/images/logo1.jpg",
  },
  {
    id: 5,
    name: "Retirement Savings Account",
    interestRate: "1.80%",
    term: "24 months",
    minimumDeposit: "£3,000",
    maximumDeposit: "£400,000",
    link: "https://example.com/product5",
    logo: "/images/logo1.jpg",
  },
  {
    id: 6,
    name: "Education Savings Account",
    interestRate: "1.60%",
    term: "12 months",
    minimumDeposit: "£1,500",
    maximumDeposit: "£200,000",
    link: "https://example.com/product6",
    logo: "/images/logo1.jpg",
  },
  {
    id: 7,
    name: "Business Savings Account",
    interestRate: "2.10%",
    term: "30 months",
    minimumDeposit: "£7,000",
    maximumDeposit: "£600,000",
    link: "https://example.com/product7",
    logo: "/images/logo1.jpg",
  },
  {
    id: 8,
    name: "Premium Savings Account",
    interestRate: "2.50%",
    term: "36 months",
    minimumDeposit: "£15,000",
    maximumDeposit: "£1,500,000",
    link: "https://example.com/product8",
    logo: "/images/logo1.jpg",
  },
  {
    id: 9,
    name: "Standard Savings Account",
    interestRate: "1.40%",
    term: "12 months",
    minimumDeposit: "£1,000",
    maximumDeposit: "£250,000",
    link: "https://example.com/product9",
    logo: "/images/logo1.jpg",
  },
  {
    id: 10,
    name: "Junior Savings Account",
    interestRate: "1.30%",
    term: "6 months",
    minimumDeposit: "£500",
    maximumDeposit: "£100,000",
    link: "https://example.com/product10",
    logo: "/images/logo1.jpg",
  },
];

export default products;
